name: Ci

on: [push, pull_request]

jobs:
  build:
    name: Check & Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 16]

    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "::set-output name=dir::$(pnpm store path)"

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install packages
        run: pnpm install 

      - name: Check & format
        run: |
          pnpm lint:check
          pnpm format:check

      - name: Build
        run: pnpm build
