name: Ci

on: [push, pull_request]

jobs:
  build:
    name: Check & Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 16]

    steps:
      - name: Setup Repository
        uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check & Format
        run: |
          yarn lint:check
          yarn format:check

      - name: Build
        run: yarn build
